import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import GeneralSans from 'next/font/local';

const generalSans = GeneralSans({
  src: './fonts/GeneralSans-Variable.ttf',
  variable: '--font-general-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${generalSans.className} antialiased`}>{children}</body>
    </html>
  );
}
